[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "starshipagentic"
version = "0.1.0"
description = "AI-assisted software development with a Star Trek-inspired interface"
readme = "README.md"
authors = [
    { name = "Travis Somerville and David Samson", email = "starshipagentic@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Code Generators",
]
requires-python = ">=3.8"
dependencies = [
    "click>=8.0.0",
    "rich>=10.0.0",
    "requests>=2.25.0",
    "tinydb>=4.5.0",
]

[project.license]
text = "GNU Affero General Public License (AGPL) v3. Note: Code output generated by Starship Agentic is licensed under the MIT License."

[project.urls]
Homepage = "https://github.com/starshipagentic/pypistarshipagentic"
"Bug Tracker" = "https://github.com/starshipagentic/pypistarshipagentic/issues"
Website = "https://www.starshipagentic.com"
"Social Media" = "https://youtube.com/@starshipagentic"
Patreon = "https://www.patreon.com/c/starshipagentic"
"Buy Me a Coffee" = "https://buymeacoffee.com/starshipagentic"

[project.scripts]
fleet_commander = "starshipagentic.commands.fleet_commander:run_group"
number_two = "starshipagentic.commands.number_two:run_group"
engineering_officer = "starshipagentic.commands.engineering_officer:run_group"
navigation_officer = "starshipagentic.commands.navigation_officer:run_group"
communications_officer = "starshipagentic.commands.communications_officer:run_group"
insterstellar_officer = "starshipagentic.commands.insterstellar_officer:run_group"
captains_orders = "starshipagentic.commands.captains_orders:run_group"
tactical_officer = "starshipagentic.commands.tactical_officer:run_group"
maintenance_officer = "starshipagentic.commands.maintenance_officer:run_group"
red_buttons = "starshipagentic.commands.red_buttons:run_group"
gitmaster = "starshipagentic.commands.gitmaster:run_group"
mcars = "starshipagentic.commands.mcars:run_group"
droids = "starshipagentic.commands.droids:run_group"
tour-ship = "starshipagentic.commands.fleet_commander.tour_ship.cli:tour_ship_command"
tour = "starshipagentic.commands.fleet_commander.tour_ship.cli:tour_ship_command"
commission-ship = "starshipagentic.commands.fleet_commander.commission_ship.cli:commission_ship_command"
commission = "starshipagentic.commands.fleet_commander.commission_ship.cli:commission_ship_command"
visualize-ship = "starshipagentic.commands.fleet_commander.visualize_ship.cli:visualize_ship_command"
mission-brief = "starshipagentic.commands.number_two.mission_brief.cli:mission_brief_command"
mission = "starshipagentic.commands.number_two.mission_brief.cli:mission_brief_command"
expand-mission = "starshipagentic.commands.number_two.expand_mission.cli:expand_mission_command"
expand = "starshipagentic.commands.number_two.expand_mission.cli:expand_mission_command"
review-schematics = "starshipagentic.commands.engineering_officer.review_schematics.cli:review_schematics_command"
schematics = "starshipagentic.commands.engineering_officer.review_schematics.cli:review_schematics_command"
calibrate-technology = "starshipagentic.commands.engineering_officer.calibrate_technology.cli:calibrate_technology_command"
calibrate = "starshipagentic.commands.engineering_officer.calibrate_technology.cli:calibrate_technology_command"
plot-navigation = "starshipagentic.commands.navigation_officer.plot_navigation.cli:plot_navigation_command"
navigation = "starshipagentic.commands.navigation_officer.plot_navigation.cli:plot_navigation_command"
set-waypoints = "starshipagentic.commands.navigation_officer.set_waypoints.cli:set_waypoints_command"
waypoints = "starshipagentic.commands.navigation_officer.set_waypoints.cli:set_waypoints_command"
authorize-codes = "starshipagentic.commands.communications_officer.authorize_codes.cli:authorize_codes_command"
authorize = "starshipagentic.commands.communications_officer.authorize_codes.cli:authorize_codes_command"
scan-sector = "starshipagentic.commands.communications_officer.scan_sector.cli:scan_sector_command"
scan = "starshipagentic.commands.communications_officer.scan_sector.cli:scan_sector_command"
receive-transmission = "starshipagentic.commands.communications_officer.receive_transmission.cli:receive_transmission_command"
transmission = "starshipagentic.commands.communications_officer.receive_transmission.cli:receive_transmission_command"
map-planet = "starshipagentic.commands.insterstellar_officer.map_planet.cli:map_planet_command"
map = "starshipagentic.commands.insterstellar_officer.map_planet.cli:map_planet_command"
build-landing-zone = "starshipagentic.commands.insterstellar_officer.build_landing_zone.cli:build_landing_zone_command"
buildlz = "starshipagentic.commands.insterstellar_officer.build_landing_zone.cli:build_landing_zone_command"
fabricate-infrastructure = "starshipagentic.commands.insterstellar_officer.fabricate_infrastructure.cli:fabricate_infrastructure_command"
fabricate = "starshipagentic.commands.insterstellar_officer.fabricate_infrastructure.cli:fabricate_infrastructure_command"
warp-speed = "starshipagentic.commands.captains_orders.warp_speed.cli:warp_speed_command"
warp = "starshipagentic.commands.captains_orders.warp_speed.cli:warp_speed_command"
trycoder = "starshipagentic.commands.captains_orders.trycoder.cli:trycoder_command"
engage = "starshipagentic.commands.captains_orders.engage.cli:engage_command"
fire-photons = "starshipagentic.commands.tactical_officer.fire_photons.cli:fire_photons_command"
photons = "starshipagentic.commands.tactical_officer.fire_photons.cli:fire_photons_command"
aim-lasers = "starshipagentic.commands.tactical_officer.aim_lasers.cli:aim_lasers_command"
lasers = "starshipagentic.commands.tactical_officer.aim_lasers.cli:aim_lasers_command"
shields-up = "starshipagentic.commands.tactical_officer.shields_up.cli:shields_up_command"
shields = "starshipagentic.commands.tactical_officer.shields_up.cli:shields_up_command"
create-checkpoint = "starshipagentic.commands.maintenance_officer.create_checkpoint.cli:create_checkpoint_command"
checkpoint = "starshipagentic.commands.maintenance_officer.create_checkpoint.cli:create_checkpoint_command"
restore-checkpoint = "starshipagentic.commands.maintenance_officer.restore_checkpoint.cli:restore_checkpoint_command"
restore = "starshipagentic.commands.maintenance_officer.restore_checkpoint.cli:restore_checkpoint_command"
inspect-vessel = "starshipagentic.commands.maintenance_officer.inspect_vessel.cli:inspect_vessel_command"
inspect = "starshipagentic.commands.maintenance_officer.inspect_vessel.cli:inspect_vessel_command"
complexity-report = "starshipagentic.commands.maintenance_officer.complexity_report.cli:complexity_report_command"
complexity = "starshipagentic.commands.maintenance_officer.complexity_report.cli:complexity_report_command"
supernova = "starshipagentic.commands.red_buttons.supernova.cli:supernova_command"
teleport = "starshipagentic.commands.gitmaster.teleport.cli:teleport_command"
search = "starshipagentic.commands.mcars.search.cli:search_command"
transport = "starshipagentic.commands.mcars.transport.cli:transport_command"
droid-splain = "starshipagentic.commands.droids.droid_splain.cli:droid_splain_command"
droid = "starshipagentic.commands.droids.droid_splain.cli:droid_splain_command"
man-splain = "starshipagentic.commands.droids.man_splain.cli:man_splain_command"
splain = "starshipagentic.commands.droids.man_splain.cli:man_splain_command"
starshipagentic = "starshipagentic.cli:main"
